name: snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake-dark.svg?palette=github-dark
            assets/snake-light.svg?palette=github-light
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
